### ISSUE TITLE
Let's update intl version

### ISSUE THREAD

**Issue by guyluz11** [channdara/flutter_localization#1]
Let's update `intl` package version

```dart
Because network_tools >=3.1.0 depends on intl ^0.18.0 and every version of flutter_localizations from sdk depends on intl 0.17.0, network_tools >=3.1.0 is incompatible with flutter_localizations from sdk.
And because easy_localization >=2.1.0+1 depends on flutter_localizations from sdk, network_tools >=3.1.0 is incompatible with easy_localization >=2.1.0+1.
So, because cybear_jinni depends on both easy_localization ^3.0.1 and network_tools ^3.1.0, version solving failed.
pub get failed
command: "/home/guyluz/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/home/guyluz/snap/flutter/common/flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "/home/guyluz/.pub-cache",
}
exit code: 1
```

**Comment by channdara** [comment]
Hello and sorry for the late reply. As the package is not using the **intl** package but it depends on the **flutter_localizations** flutter SDK which uses the **intl** package.

**Comment by guyluz11** [comment]
As I can see in the dependencies this package use the `flutter_localizations` package.
So this issue also affects us.
And if so you are right, the update should come from there not here.

![Screenshot_20230309_083022_Firefox](https://user-images.githubusercontent.com/9304740/223939371-4cc90bbd-f9ae-46ad-83e8-e9f55c9a1191.jpg)

**Comment by guyluz11** [comment]
Just saw in my posted log that it is coming from another package which is called easy_localization.
Thank you I will close this issue now
