### ISSUE TITLE
flutter_localization ^0.2.0 requires intl 0.18.1

### ISSUE THREAD

**Issue by jackfioru92** [channdara/flutter_localization#16]
I hope this message finds you well. I'm reaching out regarding an issue I encountered while working with your package, specifically related to dependency versions.

When attempting to use my app, I encountered a version conflict with flutter_localization. Here's the error message I received:

Because no versions of flutter_localization match >0.2.0 <0.3.0 and flutter_localization 0.2.0 depends on flutter_localizations from sdk, flutter_localization ^0.2.0 requires flutter_localizations from sdk.
And because every version of flutter_localizations from sdk depends on intl 0.18.1, flutter_localization ^0.2.0 requires intl 0.18.1.
So, because my app depends on both intl ^0.19.0 and flutter_localization ^0.2.0, version solving failed.

Will it be compatible with intl ^0.19.0 soon?

By the way, I'd also like to take this opportunity to compliment you on this package! Great work!

**Comment by channdara** [comment]
Hello @jackfioru92 
The **intl** version depends on the Flutter SDK **flutter_localizations**. I'm not sure when the Flutter team will upgrade the **intl** version either. Currently please use the pinned version **0.18.1** of **intl** as a workaround.

**Comment by renehw** [comment]
Some update?

**Comment by channdara** [comment]
@renehw Look like **Flutter SDK** still not yet update the **intl**, please keep using version **0.18.1** for now.

**Comment by channdara** [comment]
@Mistic92 Yes, it's the same thing for everyone. It looks like Flutter SDK **flutter_localizations** still pinned the **intl** version to **0.18.1**

**Comment by channdara** [comment]
@Boukri Still no update from **Flutter SDK** yet. Error still existed when using **intl 0.19.0** but the **0.18.1** still working fine

**Comment by yeeahh** [comment]
The intl dependency needs to be updated urgently as the updates contains the (by apple) required ios privacy manifest updates: https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by channdara** [comment]
@yeeahh If this is the case, please help report this to **Flutter SDK flutter_localizations** together to let them know.

**Comment by romatallinn** [comment]
Looks like `intl: 0.19.0` is coming in flutter [v3.21.0](https://github.com/flutter/flutter/commit/8d54abfc221e947ff387814b9c91b3a152ede269), so people pls stop annoying @channdara lol.

**Comment by romatallinn** [comment]
And FYI, something tells me that most of ppl in this thread are not even using this repo's package.

If you have this in pubspec file:
```
flutter_localizations:
  sdk: flutter
```

Then you are using [flutter/packages/flutter_localization](https://github.com/flutter/flutter/tree/master/packages/flutter_localizations), meaning you are in a totally wrong place.

Not you fault tho, they do share the exact name. 😅

**Comment by channdara** [comment]
Look like **Flutter SDK flutter_localizations** has been updated their **intl** version in the latest Flutter version. I will close this case for now. Thank you.
