### ISSUE TITLE
compatibility with firebase.

### ISSUE THREAD

**Issue by m-uzair000** [channdara/flutter_localization#18]
flutter_localizations from SDK is incompatible with firebase_core >=2.28.1.
if I add Firebase Core v 2.27.0 then it works but on the above versions it's not working.

**Comment by channdara** [comment]
Hello @m-uzair000 
I think you have reported the issue to the wrong package. Your error refers to **Flutter SDK flutter_localizations**, not this package. Sorry.

**Comment by wade-beavers** [comment]
flutter_localizations needs to update dependencies.

**Comment by m-uzair000** [comment]
thank you for pushing me on the right track.

**Comment by m-uzair000** [comment]
I have the latest one.

**Comment by channdara** [comment]
Did you try the latest version of firebase_core: ^2.31.1 yet?

**Comment by hungHatto** [comment]
Hello @channdara ,
I have same issue with web version ``` flutter_localizations from sdk depends on web 0.3.0 and firebase_messaging_web >=3.7.0 depends on web ^0.5.1, flutter_localizations from sdk is incompatible with firebase_messaging_web >=3.7.0```
