### ISSUE TITLE
Please update to intl 0.18.0

### ISSUE THREAD

**Issue by societates-civis** [channdara/flutter_localization#2]
See thread https://github.com/aissat/easy_localization/issues/560

**Comment by channdara** [comment]
Hello. I think you have referred to the wrong package as **guyluz11** mentioned here: https://github.com/aissat/easy_localization/issues/560#issuecomment-1495558499

**Comment by SamarthSerpentCS** [comment]
I faced same issue, please update intl: ^0.17.0 to 0.18.0

**Comment by channdara** [comment]
Hello @SamarthSerpentCS, the issue about intl 0.18.0 is not from this package. It's issue from Flutter ** flutter_localizations** sdk.

**Comment by kekko7072** [comment]
+ 1

**Comment by sharpsaravanan** [comment]
please update

**Comment by channdara** [comment]
People still confused the Flutter SDK **flutter_localizations** and this package (**flutter_localization**)

**Comment by channdara** [comment]
Update your Flutter to 3.10.0 might solve this problem. You can try to see if it works.

NOTE: Only for the **intl 0.18.0**. The **intl 0.18.1** still showing the error from Flutter SDK
