### ISSUE TITLE
material_color_utilities pinned to 0.8.0

### ISSUE THREAD

**Issue by under3415** [channdara/flutter_localization#21]
Hi
material_color_utilities is pinned to version 0.8.0 (released 13 months ago) by flutter_localizations from the flutter SDK. 
Is this intentional?

**Comment by channdara** [comment]
Hello @under3415 

I have no idea about this either. I think you reported to the wrong package repository. You might need to report this to the Flutter repository because the issue is caused by the Flutter SDK **flutter_localizations**

**Comment by under3415** [comment]
Plural localizations! Got it, sorry!
