### ISSUE TITLE
How to implement pluralization?

### ISSUE THREAD

**Issue by AlexeyShevchenko** [channdara/flutter_localization#23]
I'm working with a format string to display the number of available places. Depending on the number passed, the output should correctly handle pluralization. For example:

- 0 should return "no places"
- 1 should return "one place"
- 7 (or any number greater than 1) should return "7 places"

How can I implement this logic to ensure proper pluralization?

**Comment by channdara** [comment]
Hello @AlexeyShevchenko

Currently the package does not have build-in pluralization functionality, but I think you can try with the **intl** package. Can check more with this [plural method from intl package](https://pub.dev/documentation/intl/latest/intl/Intl/plural.html)

**Comment by AlexeyShevchenko** [comment]
Hello @channdara thanks for quick response 
Are you going to have such functionality in your package in future?

**Comment by channdara** [comment]
I'm looking forward to adding this functionality to the package since you have mentioned this. Thank you.

**Comment by AlexeyShevchenko** [comment]
Cool! @channdara I would like to be involved in implementation of this functionality. 
If you have some advice from where I can start please let me know.

**Comment by channdara** [comment]
I'm trying to understand the logic flow of the **plural** function from the **intl** package and integration since I don't want to add **intl** to this package to avoid conflict at a later time.

**Comment by AlexeyShevchenko** [comment]
@channdara got it
