### ISSUE TITLE
please update deps collection >=1.19.0,

### ISSUE THREAD

**Issue by manila2728** [channdara/flutter_localization#24]
Because example depends on flutter_localizations from sdk which depends on collection 1.18.0, collection 1.18.0 is required.
So, because example depends on collection >=1.19.0, version solving failed.
please update deps

**Comment by channdara** [comment]
Hello @manila2728 
Look like the issue came from Flutter SDK **flutter_localizations** and this package depend on it too. Will have to wait for Flutter SDK to update the **collection** package or you can help report this issue to [flutter](https://github.com/flutter/flutter/issues) repository.
