### ISSUE TITLE
Conflict between ScaledWidgetsFlutterBinding.ensureInitialized and LocalizedApp initialization in main function.

### ISSUE THREAD

**Issue by Jakuzeisme** [channdara/flutter_localization#25]
**Title:** Conflict between `ScaledWidgetsFlutterBinding.ensureInitialized` and `LocalizedApp` initialization in `main` function.

### Description:
Attempting to use both `ScaledWidgetsFlutterBinding.ensureInitialized` and `LocalizedApp` in the `main` function of a Flutter application results in initialization conflicts. The two libraries appear to interfere with each other when calling `runApp`, causing unexpected behavior or application crashes.

### Steps to Reproduce:
1. Initialize `ScaledWidgetsFlutterBinding.ensureInitialized` in `main`, with a `scaleFactor` callback to set the scaling based on `deviceSize`.
2. After initializing scaling, attempt to create a `LocalizationDelegate` using `flutter_translate` to support multiple locales.
3. Pass `LocalizedApp(delegate, MyApp())` to `runApp`.

```dart
void main() async {
  // Initialize scaling
  ScaledWidgetsFlutterBinding.ensureInitialized(
    scaleFactor: (deviceSize) {
      const double widthOfDesign = 375;
      return deviceSize.width / widthOfDesign;
    },
  );

  // Initialize localization
  var delegate = await LocalizationDelegate.create(
      fallbackLocale: 'en_US',
      supportedLocales: ['en_US', 'es', 'fa', 'ar', 'ru']);

  // Run the app with localization
  runApp(LocalizedApp(delegate, MyApp()));
}
```

### Expected Behavior:
The application should start with scaling applied to widgets and localization properly initialized for supported locales.

### Actual Behavior:
The initialization process conflicts, likely because `ScaledWidgetsFlutterBinding` and `LocalizedApp` both attempt to set up configurations for `runApp`. This causes unexpected behavior, such as widget scaling not applying correctly, localization issues, or the app failing to launch altogether.

### Environment:
- Flutter version: [Specify your Flutter version]
- Packages:
  - `flutter_translate` and flutter_localization: latest 
  - `scaled_app`

### Additional Information:
If scaling or localization is removed, the app launches as expected, indicating that the conflict arises from using both together in `main`. It happens more clearly in debug mode

**Comment by channdara** [comment]
Hello @Jakuzeisme 

- First of all, I have go through your example code and make a test in fresh new project but seem to not receiving any error at all. The app run normally.
- Secondly, seem like the issue you have faced with are not related to this package at all. You have mentioned conflict between **scaled_app** and **flutter_translate** packages.
- I see you mention **flutter_localization: latest** in the **Environment** section, but I think you might confuse with **flutter_localizations from Flutter SDK**, correct me if I'm wrong with this one, sorry. 

Anyway, if you can provide more information related with the error log in the console, I might be able to help you with this issue. Thank you.

**Comment by Jakuzeisme** [comment]
Thanks for the early response and yes you're right. Sorry about that mistake.
But I wish you could help me look into it. It happens in debug mode only.. the flutter app is stuck at splash screen

Code:
void main() async {
  // Initialize scaling
  ScaledWidgetsFlutterBinding.ensureInitialized(
    scaleFactor: (deviceSize) {
      const double widthOfDesign = 375;
      return deviceSize.width / widthOfDesign;
    },
  );

  // Initialize localization
  var delegate = await LocalizationDelegate.create(
      fallbackLocale: 'en_US',
      supportedLocales: ['en_US', 'es', 'fa', 'ar', 'ru']);

  // Run the app with localization
  runApp(LocalizedApp(delegate, MyApp()));
}


Error:
Binding has not yet been initialized.
I/flutter (30081): The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized.
I/flutter (30081): Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.
I/flutter (30081): In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding.
I/flutter (30081): If ServicesBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter.



//SCALE CLASS
import 'dart:async' show scheduleMicrotask, Timer;
import 'dart:collection' show Queue;
import 'dart:ui' show PointerDataPacket;

import 'package:flutter/gestures.dart' show FlutterView, PointerEventConverter;
import 'package:flutter/rendering.dart' show RenderView, ViewConfiguration;
import 'package:flutter/widgets.dart';

/// The size of the screen is in logical pixels.
///
// of 1 means original size.
///
typedef ScaleFactorCallback = double Function(Size deviceSize);

/// Replace [runApp] with [runAppScaled] in `main()`.
///
/// Scaling will be applied based on [scaleFactor] callback.
///
void runAppScaled(Widget app, {ScaleFactorCallback? scaleFactor}) {
  WidgetsBinding binding = ScaledWidgetsFlutterBinding.ensureInitialized(
    scaleFactor: scaleFactor,
  );
  Timer.run(() {
    binding.attachRootWidget(binding.wrapWithDefaultView(app));
  });
  binding.scheduleWarmUpFrame();
}

/// Adapted from [WidgetsFlutterBinding]
///
class ScaledWidgetsFlutterBinding extends WidgetsFlutterBinding {
  /// Calculate scale factor from device size.
  ScaleFactorCallback? _scaleFactor;

  ScaledWidgetsFlutterBinding._({ScaleFactorCallback? scaleFactor})
      : _scaleFactor = scaleFactor;

  ScaleFactorCallback get scaleFactor => _scaleFactor ?? (_) => 1.0;

  /// Update scaleFactor callback, then rebuild layout
  set scaleFactor(ScaleFactorCallback? callback) {
    _scaleFactor = callback;
    handleMetricsChanged();
  }

  double get scale {
    final FlutterView view = platformDispatcher.implicitView!;
    final devicePixelRatio = view.devicePixelRatio;
    final physicalSize = view.physicalSize;
    return scaleFactor(physicalSize / devicePixelRatio);
  }

  double devicePixelRatioScaled = 0;

  bool get isScaling => scale != 1.0;

  static ScaledWidgetsFlutterBinding? _binding;

  /// Scaling will be applied based on [scaleFactor] callback.
  ///
  static WidgetsBinding ensureInitialized({ScaleFactorCallback? scaleFactor}) {
    _binding ??= ScaledWidgetsFlutterBinding._(scaleFactor: scaleFactor);
    return _binding!;
  }

  static ScaledWidgetsFlutterBinding get instance => _binding!;

  /// Override the method from [RendererBinding.createViewConfiguration] to
  /// change what size or device pixel ratio the [RenderView] will use.
  ///
  /// See more:
  /// * [RendererBinding.createViewConfiguration]
  /// * [TestWidgetsFlutterBinding.createViewConfiguration]
  @override
  ViewConfiguration createViewConfigurationFor(RenderView renderView) {
    final FlutterView view = platformDispatcher.implicitView!;
    final devicePixelRatio = view.devicePixelRatio;
    final physicalSize = view.physicalSize;

    if (physicalSize.isEmpty) {
      return super.createViewConfigurationFor(renderView);
    } else {
      devicePixelRatioScaled = devicePixelRatio * scale;

      final BoxConstraints physicalConstraints =
          BoxConstraints.fromViewConstraints(view.physicalConstraints);
      return ViewConfiguration(
        physicalConstraints: physicalConstraints,
        logicalConstraints: physicalConstraints / devicePixelRatioScaled,
        devicePixelRatio: devicePixelRatioScaled,
      );
    }
  }

  // @override
  // SingletonFlutterWindow get window => super.window;

  /// Adapted from [GestureBinding.initInstances]
  @override
  void initInstances() {
    super.initInstances();
    platformDispatcher.onPointerDataPacket = _handlePointerDataPacket;
    //  WidgetsBinding.instance.addObserver(this);
  }

  // Add a listener for ZoomNotifier
  void setZoom(double scale) {
    _scaleFactor = (_) => scale;
    handleMetricsChanged();
  }

  @override
  void unlocked() {
    super.unlocked();
    _flushPointerEventQueue();
  }

  final Queue<PointerEvent> _pendingPointerEvents = Queue<PointerEvent>();

  /// When we scale UI using [ViewConfiguration], [ui.window] stays the same.
  ///
  /// [GestureBinding] uses [platformDispatcher.implicitView.devicePixelRatio] for calculations,
  /// so we override corresponding methods.
  ///
  void _handlePointerDataPacket(PointerDataPacket packet) {
    // We convert pointer data to logical pixels so that e.g. the touch slop can be
    // defined in a device-independent manner.
    try {
      _pendingPointerEvents.addAll(PointerEventConverter.expand(
        packet.data,
        (viewId) {
          return devicePixelRatioScaled;
        },
      ));
      if (!locked) {
        _flushPointerEventQueue();
      }
    } catch (error, stack) {
      FlutterError.reportError(FlutterErrorDetails(
        exception: error,
        stack: stack,
        library: 'gestures library',
        context:
            ErrorDescription('while handling a scaled pointer data packet'),
      ));
    }
  }

  /// Dispatch a [PointerCancelEvent] for the given pointer soon.
  ///
  /// The pointer event will be dispatched before the next pointer event and
  /// before the end of the microtask but not within this function call.
  @override
  void cancelPointer(int pointer) {
    if (_pendingPointerEvents.isEmpty && !locked) {
      scheduleMicrotask(_flushPointerEventQueue);
    }
    _pendingPointerEvents.addFirst(PointerCancelEvent(pointer: pointer));
  }

  void _flushPointerEventQueue() {
    assert(!locked);

    while (_pendingPointerEvents.isNotEmpty) {
      handlePointerEvent(_pendingPointerEvents.removeFirst());
    }
  }
}

extension ScaledMediaQueryData on MediaQueryData {

  MediaQueryData scale() {
    final scale = (ScaledWidgetsFlutterBinding._binding?.scale ?? 1);
    return copyWith(
      size: size / scale,
      devicePixelRatio: devicePixelRatio * scale,
      viewInsets: viewInsets / scale,
      viewPadding: viewPadding / scale,
      padding: padding / scale,
    );
  }
    MediaQueryData scaleUp() {
    final scale = (ScaledWidgetsFlutterBinding._binding?.scale ?? 1);
    return copyWith(
      size: size * scale,
      devicePixelRatio: devicePixelRatio / scale,
      viewInsets: viewInsets * scale,
      viewPadding: viewPadding * scale,
      padding: padding * scale,
    );
  }
}

///LOCALIZED APP
import 'package:flutter/widgets.dart';
import 'package:flutter_translate/flutter_translate.dart';

class LocalizedApp extends StatefulWidget {
  final Widget child;

  final LocalizationDelegate delegate;

  LocalizedApp(this.delegate, this.child);

  LocalizedAppState createState() => LocalizedAppState();

  static LocalizedApp of(BuildContext context) =>
      context.findAncestorWidgetOfExactType<LocalizedApp>()!;
}

**Comment by channdara** [comment]
The code I use look similar as you have mentioned too but I'm not be able to reproduce the issue. I can run the app normally without any error log in console.
```dart
Future<void> main() async {
  ScaledWidgetsFlutterBinding.ensureInitialized(
    scaleFactor: (device) => device.width / 375,
  );
  final delegate = await LocalizationDelegate.create(
    fallbackLocale: 'en_US',
    supportedLocales: ['en_US', 'es', 'fa'],
  );
  runApp(LocalizedApp(delegate, const Application()));
}

class Application extends StatefulWidget {
  const Application({super.key});

  @override
  State<Application> createState() => _ApplicationState();
}

class _ApplicationState extends State<Application> {
  @override
  Widget build(BuildContext context) {
    final localizationDelegate = LocalizedApp.of(context).delegate;
    return LocalizationProvider(
      state: LocalizationProvider.of(context).state,
      child: MaterialApp(
        home: const MainScreen(),
        localizationsDelegates: [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          localizationDelegate
        ],
        supportedLocales: localizationDelegate.supportedLocales,
        locale: localizationDelegate.currentLocale,
      ),
    );
  }
}
```

**Comment by Jakuzeisme** [comment]
Thanks a lot, the solution was using LocalizationProvider..

I really appreciate u, thank u

**Comment by ctrlygreaterthanctrlz** [comment]
@channdara 
Yo my man I follow your stuff but this is completely unrelated and I've been stuck here for a while.

I'm trying to build an Android app with flutter that needs to create a PDF file in public external storage, specifically at the path: /storage/emulated/0/Mypdfs/my_pdf.pdf.//an example

1. For Android 10 and below, can I simply use READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE permissions to create and write the PDF in public storage?


2. For Android 11 and above, is MANAGE_EXTERNAL_STORAGE really necessary for just creating a PDF, or can I use READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE permissions to save it? I know Google has strict policies about MANAGE_EXTERNAL_STORAGE for publishing apps, so I want to avoid it unless absolutely needed.
3. I'm trying to publish the app, I'm stuck on this 2 weeks app testers stuff and the app is being thoroughly checked cos of this . I just want to 100% sure. Would love your opinion on this
