### ISSUE TITLE
Is it supported to use parameters?

### ISSUE THREAD

**Issue by sun-jiao** [channdara/flutter_localization#33]
Something like:

```
map = {
  iAM = "I am {name}.";
};
AppLocale.iAM.getString(context, name: Jack);
// "I am Jack."

```

**Comment by channdara** [comment]
Hi @sun-jiao 

The package provided similar function you wanted, but I'm not sure if it complete to what you wanted or not.
You can check at the **Some update note** -> **Version 0.1.13** section in the Readme.

```dart
Strings.format('Hello %a, this is me %a.', ['Dara', 'Sopheak']);
// Result: Hello Dara, this is me Sopheak.

context.formatString('This is %a package, version %a.', [AppLocale.title, 'LATEST'])
// Result: This is Localization package, version LATEST.
```

**Comment by sun-jiao** [comment]
> Hi @sun-jiao
> 
> The package provided similar function you mentioned, but I'm not sure if it complete to what you wanted or not. You can check at the **Some update note** -> **Version 0.1.13** section in the Readme.
> 
> ```dart
> Strings.format('Hello %a, this is me %a.', ['Dara', 'Sopheak']);
> // Result: Hello Dara, this is me Sopheak.
> 
> context.formatString('This is %a package, version %a.', [AppLocale.title, 'LATEST'])
> // Result: This is Localization package, version LATEST.
> ```

So it's parsing it using the dart default parser?

**Comment by channdara** [comment]
@sun-jiao it's just a custom function and extension that help with localization.

Example related with what you mentioned:
```
map = {
  "iAM" = "I am %a.";
};

context.formatString(map["iAM"], ["Jack"])
// Result: I am Jack.
```

If you use the **context.formatString** extension, all text will be parsing with localization, but if you use **Strings.format** function, you need to manually localize those text for the function.
