### ISSUE TITLE
how to handle localization key is not found in the locale file?

### ISSUE THREAD

**Issue by Kancheraj** [channdara/flutter_localization#4]

**Comment by channdara** [comment]
The localization key is not found due to it not being added in all the locale map data. You need those missing keys to all your locale map data that you use in the app.

If I'm getting your question wrong, please provide more information about your error. Thank you.

**Comment by vibhashan** [comment]
Same here. 

mixin AppLocale {
  // static const String title = 'title';
  static const String sampleText = 'sampleText';

  static const Map<String, dynamic> EN = {
    // title: 'Localization',
    sampleText: 'Hello',
  };
  static const Map<String, dynamic> SI = {
    // title: 'සිංහල',
    sampleText: 'Hello',
  };
}

The above is my file. But I can't use sampleText. It says "sampleText not found"

**Comment by vibhashan** [comment]
`mixin AppLocale {
  static const String title = 'title';
  static const String sampleText = 'sampleText';

  static const Map<String, dynamic> EN = {
    title: 'Localization',
    sampleText: 'Hello',
  };
  static const Map<String, dynamic> SI = {
    title: 'සිංහල',
    sampleText: 'Hello',
  };
}`

Here is a more readable code

**Comment by channdara** [comment]
Hello @vibhashan 
Did you provide **supportedLocales** and **localizationsDelegates** to the **MaterialApp** in your app?

**Comment by vibhashan** [comment]
Yes I did...the key "title" is working fine...only issue is when I try to
add a new key value for example "abc"

**Comment by channdara** [comment]
@vibhashan I will check that. But make sure to re-run the app after adding a new key and value to the map data. Hot reload will not work and show the error "key not found"

**Comment by vibhashan** [comment]
Ohh okay. I did not actually re run the app instead performed hot reload.
I'll check this and get back to you

**Comment by vibhashan** [comment]
Hi. Thanks for the tip. Actually after rerunning, all the new key-values and translations are working. Thanks brother, saved my day 😎🙌🔥
