### ISSUE TITLE
how to pass a paramter to be added to strings localized like "Here is the number:$number"

### ISSUE THREAD

**Issue by EgHubs** [channdara/flutter_localization#8]
I use these two classes for localization in flutter
following this [article](https://medium.com/flutter-community/multi-language-support-in-flutter-a12de708f833) setup.
```
import 'package:flutter/cupertino.dart';

abstract class Languages {
  final String? extra;

  Languages({this.extra});
  static Languages? of(BuildContext context, {String? extra}) {
    return Localizations.of<Languages>(context, Languages);
  }
String get text199;
}

```

and this LanguageEn:

```
import 'languages.dart';

class LanguageEn extends Languages
{
  LanguageEn({String? extra}) : super(extra: extra);
  @override
String get text199 => "Update data($extra)";
}
```

when I pass this extra parameter I get null `"Update data(null)"` in whatever language I'm in

` Languages.of(context,extra: "$activeID")!.text199),
`

but when I directly select a language class and do this it works and I get the number and not null `"Update data(4)"`

` LanguageEn(extra: "$activeID").text199),
`                                                    

how to pass dynamic strings with this package?

**Comment by channdara** [comment]
Hello. I think you have reported the issue to the wrong package. This package is **flutter_localization**, the package you are using is the Flutter SDK **flutter_localizations**.
